import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { checkVersion, setVersion } from '../scripts/version.mjs';

const roots: string[] = [];
type JsonObject = Record<string, unknown>;
type DriftCase = [string, string, string, (value: JsonObject) => void];

const driftCases: DriftCase[] = [
  [
    'package-lock root',
    'package-lock.json',
    'package-lock.json#version',
    (value) => (value.version = '0.7.3'),
  ],
  [
    'package-lock package',
    'package-lock.json',
    'package-lock.json#packages[""].version',
    (value) => {
      const packages = value.packages as Record<string, { version: string }>;
      packages[''].version = '0.7.3';
    },
  ],
  ['server manifest', 'server.json', 'server.json#version', (value) => (value.version = '0.7.3')],
  [
    'server package',
    'server.json',
    'server.json#packages[noxctl].version',
    (value) => {
      const packages = value.packages as Array<{ version: string }>;
      packages[0].version = '0.7.3';
    },
  ],
];

async function writeJson(filePath: string, value: unknown): Promise<void> {
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

async function createFixture(version = '0.7.4'): Promise<string> {
  const root = await mkdtemp(path.join(tmpdir(), 'noxctl-version-test-'));
  roots.push(root);
  await mkdir(path.join(root, 'src'));
  await writeJson(path.join(root, 'package.json'), { name: 'noxctl', version });
  await writeJson(path.join(root, 'package-lock.json'), {
    name: 'noxctl',
    version,
    lockfileVersion: 3,
    packages: { '': { name: 'noxctl', version } },
  });
  await writeJson(path.join(root, 'server.json'), {
    name: 'io.github.magnus-gille/noxctl',
    version,
    packages: [{ registryType: 'npm', identifier: 'noxctl', version }],
  });
  await writeFile(
    path.join(root, 'src/version.ts'),
    `// Generated by scripts/version.mjs. Do not edit manually.\nexport const VERSION = '${version}' as const;\n`,
    'utf8',
  );
  return root;
}

async function snapshot(root: string): Promise<Record<string, string>> {
  const files = ['package.json', 'package-lock.json', 'server.json', 'src/version.ts'];
  return Object.fromEntries(
    await Promise.all(
      files.map(async (file) => [file, await readFile(path.join(root, file), 'utf8')]),
    ),
  );
}

afterEach(async () => {
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe('version tooling', () => {
  it('runs the read-only check in verification and every CI platform job', async () => {
    const packageJson = JSON.parse(await readFile(path.resolve('package.json'), 'utf8')) as {
      scripts: Record<string, string>;
    };
    const workflow = await readFile(path.resolve('.github/workflows/ci.yml'), 'utf8');

    expect(packageJson.scripts.verify).toContain('npm run version:check');
    expect(workflow.match(/- run: npm run version:check/g)).toHaveLength(2);
  });

  it('documents the automated release version workflow', async () => {
    const contributing = await readFile(path.resolve('CONTRIBUTING.md'), 'utf8');

    expect(contributing).toContain('npm run version:set -- X.Y.Z');
    expect(contributing).toContain('npm run version:check');
    expect(contributing).not.toContain('Bump the version in **five files**');
  });

  it('accepts a fully synchronized tree', async () => {
    const root = await createFixture();

    await expect(checkVersion(root)).resolves.toBe('0.7.4');
  });

  it.each(driftCases)('rejects drift in %s', async (_label, file, location, mutate) => {
    const root = await createFixture();
    const filePath = path.join(root, file);
    const value = JSON.parse(await readFile(filePath, 'utf8')) as JsonObject;
    mutate(value);
    await writeJson(filePath, value);

    await expect(checkVersion(root)).rejects.toThrow(`${location}: expected 0.7.4, found 0.7.3`);
  });

  it('rejects generated-source drift', async () => {
    const root = await createFixture();
    await writeFile(
      path.join(root, 'src/version.ts'),
      "// Generated by scripts/version.mjs. Do not edit manually.\nexport const VERSION = '0.7.3' as const;\n",
      'utf8',
    );

    await expect(checkVersion(root)).rejects.toThrow(
      'src/version.ts#VERSION: expected 0.7.4, found 0.7.3',
    );
  });

  it('accepts the generated source after a Windows CRLF checkout', async () => {
    const root = await createFixture();
    const sourcePath = path.join(root, 'src/version.ts');
    const source = await readFile(sourcePath, 'utf8');
    await writeFile(sourcePath, source.replaceAll('\n', '\r\n'), 'utf8');

    await expect(checkVersion(root)).resolves.toBe('0.7.4');
  });

  it.each(['1.2', 'v1.2.3', '01.2.3', '1.2.3-01', ''])(
    'rejects invalid SemVer %j without writing files',
    async (version) => {
      const root = await createFixture();
      const before = await snapshot(root);

      await expect(setVersion(root, version)).rejects.toThrow('Invalid semantic version');
      await expect(snapshot(root)).resolves.toEqual(before);
    },
  );

  it('updates every tracked value atomically per file and is idempotent', async () => {
    const root = await createFixture();

    await expect(setVersion(root, '0.8.0')).resolves.toEqual([
      'package.json',
      'package-lock.json',
      'server.json',
      'src/version.ts',
    ]);
    await expect(checkVersion(root)).resolves.toBe('0.8.0');
    const packageLock = JSON.parse(
      await readFile(path.join(root, 'package-lock.json'), 'utf8'),
    ) as { lockfileVersion: number };
    expect(packageLock.lockfileVersion).toBe(3);
    await expect(setVersion(root, '0.8.0')).resolves.toEqual([]);
  });

  it('accepts a valid SemVer prerelease and build identifier', async () => {
    const root = await createFixture();

    await setVersion(root, '0.8.0-rc.1+build.2');

    await expect(checkVersion(root)).resolves.toBe('0.8.0-rc.1+build.2');
  });

  it('validates every manifest before writing any file', async () => {
    const root = await createFixture();
    const before = await snapshot(root);
    await writeFile(path.join(root, 'server.json'), '{ broken json', 'utf8');
    const broken = await snapshot(root);

    await expect(setVersion(root, '0.8.0')).rejects.toThrow('server.json is not valid JSON');
    await expect(snapshot(root)).resolves.toEqual(broken);
    expect(broken['package.json']).toBe(before['package.json']);
  });
});
