import { randomUUID } from 'node:crypto';
import { readFile, rename, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const DEFAULT_ROOT = path.resolve(path.dirname(SCRIPT_PATH), '..');
const SEMVER_PATTERN =
  /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/;
const VERSION_SOURCE_PATTERN =
  /^\/\/ Generated by scripts\/version\.mjs\. Do not edit manually\.\r?\nexport const VERSION = '([^']+)' as const;\r?\n$/;

function isObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function requireObject(value, description) {
  if (!isObject(value)) throw new Error(`${description} must be an object`);
  return value;
}

function requireString(value, description) {
  if (typeof value !== 'string') throw new Error(`${description} must be a string`);
  return value;
}

function versionSource(version) {
  return `// Generated by scripts/version.mjs. Do not edit manually.\nexport const VERSION = '${version}' as const;\n`;
}

async function readText(root, relativePath) {
  try {
    return await readFile(path.join(root, relativePath), 'utf8');
  } catch (error) {
    throw new Error(`Could not read ${relativePath}: ${error.message}`);
  }
}

async function readJson(root, relativePath) {
  const contents = await readText(root, relativePath);
  try {
    return { contents, value: JSON.parse(contents) };
  } catch (error) {
    throw new Error(`${relativePath} is not valid JSON: ${error.message}`);
  }
}

async function loadState(root) {
  const [packageFile, lockFile, serverFile, sourceContents] = await Promise.all([
    readJson(root, 'package.json'),
    readJson(root, 'package-lock.json'),
    readJson(root, 'server.json'),
    readText(root, 'src/version.ts'),
  ]);

  const packageJson = requireObject(packageFile.value, 'package.json');
  const packageVersion = requireString(packageJson.version, 'package.json version');
  if (!SEMVER_PATTERN.test(packageVersion)) {
    throw new Error(`package.json has invalid semantic version: ${packageVersion}`);
  }

  const packageLock = requireObject(lockFile.value, 'package-lock.json');
  const lockVersion = requireString(packageLock.version, 'package-lock.json version');
  const lockPackages = requireObject(packageLock.packages, 'package-lock.json packages');
  const lockRoot = requireObject(lockPackages[''], 'package-lock.json root package');
  const lockRootVersion = requireString(
    lockRoot.version,
    'package-lock.json root package version',
  );

  const serverJson = requireObject(serverFile.value, 'server.json');
  const serverVersion = requireString(serverJson.version, 'server.json version');
  if (!Array.isArray(serverJson.packages)) throw new Error('server.json packages must be an array');
  const serverPackages = serverJson.packages.filter(
    (entry) => isObject(entry) && entry.identifier === 'noxctl',
  );
  if (serverPackages.length !== 1) {
    throw new Error('server.json must contain exactly one noxctl package entry');
  }
  const serverPackage = serverPackages[0];
  const serverPackageVersion = requireString(
    serverPackage.version,
    'server.json noxctl package version',
  );

  const sourceMatch = VERSION_SOURCE_PATTERN.exec(sourceContents);
  if (!sourceMatch) {
    throw new Error('src/version.ts does not match the generated version format');
  }

  return {
    packageFile,
    packageJson,
    packageVersion,
    lockFile,
    packageLock,
    lockRoot,
    lockVersion,
    lockRootVersion,
    serverFile,
    serverJson,
    serverPackage,
    serverVersion,
    serverPackageVersion,
    sourceContents,
    sourceVersion: sourceMatch[1],
  };
}

function mismatch(location, expected, found) {
  return `${location}: expected ${expected}, found ${found}`;
}

export async function checkVersion(root = DEFAULT_ROOT) {
  const state = await loadState(path.resolve(root));
  const expected = state.packageVersion;
  const mismatches = [];

  if (state.lockVersion !== expected) {
    mismatches.push(mismatch('package-lock.json#version', expected, state.lockVersion));
  }
  if (state.lockRootVersion !== expected) {
    mismatches.push(
      mismatch('package-lock.json#packages[""].version', expected, state.lockRootVersion),
    );
  }
  if (state.serverVersion !== expected) {
    mismatches.push(mismatch('server.json#version', expected, state.serverVersion));
  }
  if (state.serverPackageVersion !== expected) {
    mismatches.push(
      mismatch('server.json#packages[noxctl].version', expected, state.serverPackageVersion),
    );
  }
  if (state.sourceVersion !== expected) {
    mismatches.push(mismatch('src/version.ts#VERSION', expected, state.sourceVersion));
  }

  if (mismatches.length > 0) {
    throw new Error(`Version mismatch:\n- ${mismatches.join('\n- ')}`);
  }
  return expected;
}

async function writeAtomically(filePath, contents) {
  const temporaryPath = `${filePath}.${process.pid}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporaryPath, contents, { encoding: 'utf8', flag: 'wx' });
    await rename(temporaryPath, filePath);
  } finally {
    await rm(temporaryPath, { force: true });
  }
}

export async function setVersion(root = DEFAULT_ROOT, version) {
  if (typeof version !== 'string' || !SEMVER_PATTERN.test(version)) {
    throw new Error(`Invalid semantic version: ${JSON.stringify(version)}`);
  }

  const resolvedRoot = path.resolve(root);
  const state = await loadState(resolvedRoot);
  state.packageJson.version = version;
  state.packageLock.version = version;
  state.lockRoot.version = version;
  state.serverJson.version = version;
  state.serverPackage.version = version;

  const candidates = [
    ['package.json', `${JSON.stringify(state.packageJson, null, 2)}\n`, state.packageFile.contents],
    [
      'package-lock.json',
      `${JSON.stringify(state.packageLock, null, 2)}\n`,
      state.lockFile.contents,
    ],
    ['server.json', `${JSON.stringify(state.serverJson, null, 2)}\n`, state.serverFile.contents],
    ['src/version.ts', versionSource(version), state.sourceContents],
  ];
  const changed = candidates.filter(([, next, current]) => next !== current);
  for (const [relativePath, contents] of changed) {
    await writeAtomically(path.join(resolvedRoot, relativePath), contents);
  }
  return changed.map(([relativePath]) => relativePath);
}

async function main(args) {
  const [command, value, ...extra] = args;
  if (command === 'check' && value === undefined && extra.length === 0) {
    const version = await checkVersion();
    process.stdout.write(`Version ${version} is synchronized.\n`);
    return;
  }
  if (command === 'set' && value !== undefined && extra.length === 0) {
    const changed = await setVersion(DEFAULT_ROOT, value);
    process.stdout.write(
      changed.length > 0
        ? `Set version ${value} in ${changed.join(', ')}.\n`
        : `Version ${value} is already synchronized.\n`,
    );
    return;
  }
  throw new Error('Usage: node scripts/version.mjs check | set <semver>');
}

if (process.argv[1] && path.resolve(process.argv[1]) === SCRIPT_PATH) {
  main(process.argv.slice(2)).catch((error) => {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
  });
}
